stages:
  - package

package:
  stage: package
  image: registry.git.alteryx.com/hamilton/docker-builder
  script:
    - python3 setup.py sdist bdist_wheel
    - twine upload --config-file .pypirc -r local -u $ARTIFACTORY_USERNAME -p $ARTIFACTORY_PASSWORD dist/* --verbose
    - twine upload dist/*
  variables:
    GIT_SUBMODULE_STRATEGY: normal
  dependencies: [numpy]
  only:
    - master
  tags:
    - linux-docker
